2020-07-18 19:55:10,520 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2020-07-18 19:55:10,539 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'ssh']
2020-07-18 19:55:10,542 DEBUG    root            Running [gcloud.compute.ssh] with arguments: [[USER@]INSTANCE: "twitter-hatena"]
2020-07-18 19:55:11,229 INFO     ___FILE_ONLY___ No zone specified. Using zone [us-central1-a] for instance: [twitter-hatena].

2020-07-18 19:55:12,021 DEBUG    root            Current SSH keys in project: ['ganariya:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWVy0G/DRfm58WF1KktoWl5W4D10rB17lBe/Nh9xD7EG+qwOsC25LrToXO6g/Bqsxgxx8QO8W+9Xs0c0D8edC0ADZfJrzkT7qeJwwlurp64nQjqZKKSVH43RWHnHAqwjnSZl1MdJlliHfJ5ZwqFPQc5Z+y9WFmTy8/pN2W84f/5rGCnkmkJyKAxUYBvHQnB+XopUdgGzRanUyTx6RyRQEBOV4kGVxPWNHVmkUY/d2eXXjz4OS9hMsJItPir8oDbcrhsrKetUWkOnjeOBDY0TeMMExtDjN972i6cH/EAMdUy6JVRKQQaafcRI4vy2lmUjictiX1euSrhOeTZDLIJ1/Qi6lytNwfpDl377mvfjZa5ABUAV9st8eOpv1lBq239baUMWZ1VgijFe/pAJXRBvp3JjToQKchjxZISAQj3RA5mO1buX6h9A74jx1OirJuRatxTGnb6pPYOtRCnR0+7YnNZ7jGDauV4z1GrDWCu9Tr9U5OymRhBN1AphAx7DH6DKU= ganariya@ganariyamac.local']
2020-07-18 19:55:12,021 DEBUG    root            Running command [/usr/bin/ssh -t -i /Users/ganariya/.ssh/google_compute_engine -o CheckHostIP=no -o HostKeyAlias=compute.4755784977998637613 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/Users/ganariya/.ssh/google_compute_known_hosts ganariya@107.178.212.170].
2020-07-18 19:55:12,021 DEBUG    root            Executing command: ['/usr/bin/ssh', '-t', '-i', '/Users/ganariya/.ssh/google_compute_engine', '-o', 'CheckHostIP=no', '-o', 'HostKeyAlias=compute.4755784977998637613', '-o', 'IdentitiesOnly=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/Users/ganariya/.ssh/google_compute_known_hosts', 'ganariya@107.178.212.170']
2020-07-18 20:23:50,452 DEBUG    root            (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Traceback (most recent call last):
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/compute/ssh.py", line 265, in Run
    return_code = cmd.Run(ssh_helper.env, force_connect=True)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/ssh/ssh.py", line 1269, in Run
    raise CommandError(args[0], return_code=status)
googlecloudsdk.command_lib.util.ssh.ssh.CommandError: [/usr/bin/ssh] exited with return code [255].
2020-07-18 20:23:50,493 ERROR    root            (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
